### ISSUE TITLE
nginx: [emerg] host not found in upstream "app" in /etc/nginx/nginx.conf:24

### ISSUE THREAD

**Issue by cmthomps** [awslabs/ecs-nginx-reverse-proxy#4]
When I attempt to deploy this, the nginx container fails and stops with an error "nginx: [emerg] host not found in upstream "app" in /etc/nginx/nginx.conf:24".  It seems like the internal name resolution doesn't work.  I was having a similar problem with another project and then just tried to deploy this project as is.  Has something changed in ECS since this was developed?

Full log:

--------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                             message                                              |
|---------------|--------------------------------------------------------------------------------------------------|
| 1609878836789 | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration |
| 1609878836789 | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/                        |
| 1609878836792 | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh            |
| 1609878836795 | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf    |
| 1609878836804 | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf  |
| 1609878836805 | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh                |
| 1609878836809 | /docker-entrypoint.sh: Configuration complete; ready for start up                                |
| 1609878836823 | 2021/01/05 20:33:56 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/nginx.conf:24    |
| 1609878836823 | nginx: [emerg] host not found in upstream "app" in /etc/nginx/nginx.conf:24                      |
--------------------------------------------------------------------------------------------------------------------

**Comment by dfelski** [comment]
I'm also facing a similar issue trying this approach, it looks like the host name can't be resolved with this setup anymore.

`...myapp could not be resolved (3: Host not found)...`

**Comment by htchaan** [comment]
In my case, the hostname lookup failed because the ECS task is not up yet.
```yml
depends_on:
      - app
```

Btw from the official [docker compose documentation](https://docs.docker.com/cloud/ecs-compose-features/), `service.links` is not (no longer?) implemented.

**Comment by oussaka** [comment]
try adding this :

```
    web:
        image: nginx:alpine
        working_dir: /app
        restart: unless-stopped
        volumes:
            - .:/app
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        port:
           - ...
        depends_on:
            - php-fpm
        networks:
            - nginx_net

    app:
        image: php:7-fpm
        working_dir: /app
        restart: unless-stopped
        volumes:
            - .:/app
            - ...
        environment:
            ....
        networks:
            - nginx_net
            
```
